--- 
knit: "bookdown::render_book"
title: "Uderstanding Survey Sampling"
author: "Lingyun Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
links-as-notes: true
colorlinks: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Preface {-}

How do you learn, or to be exact, how do you learn complex stuff? I guess that many different answers will come out, because we are all different in many aspects, such as culture background, knowledge level, and learning style etc. etc.. For myself, if I want to seriously learn some complex stuff, then I will write about it. Without doubts, *sampling* (or to be exact, *survey sampling*) is complex, and it is kind of boring, but it is important (for me, because I need it for my work, and for you the reasons may be different). So I have to learn and re-learn sampling, and this results in the current book.

No matter what we want to study/learn, in my opinion---probably you agree with me---**understanding** is the most important goal that we want to archive. For understanding, we must focus our attention on **what**, **how** and **why**, with unequal emphasis, depending on circumstances. A good starting point of learning about survey sampling is a couple of what questions:

- What is a *sample*?
- What is a good sample?

We cover these questions especially the answers to them in Chapter \@ref(sample).
